#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : wxhexeditor
Version  : 0.24
Release  : 230
URL      : file:///aot/build/clearlinux/packages/wxhexeditor/wxhexeditor-v0.24.tar.gz
Source0  : file:///aot/build/clearlinux/packages/wxhexeditor/wxhexeditor-v0.24.tar.gz
Summary  : Thread-safe hash library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.0
Requires: wxhexeditor-bin = %{version}-%{release}
Requires: wxhexeditor-data = %{version}-%{release}
BuildRequires : binutils-dev
BuildRequires : buildreq-cmake
BuildRequires : bzip2-dev
BuildRequires : bzip2-staticdev
BuildRequires : capstone
BuildRequires : capstone-dev
BuildRequires : compat-lua-53
BuildRequires : compat-lua-53-dev
BuildRequires : file
BuildRequires : file-abi
BuildRequires : file-bin
BuildRequires : file-data
BuildRequires : file-dev
BuildRequires : file-lib
BuildRequires : file-license
BuildRequires : file-man
BuildRequires : file-staticdev
BuildRequires : gcc
BuildRequires : gcc-dev
BuildRequires : gcc-doc
BuildRequires : gcc-libs-math
BuildRequires : gcc-libubsan
BuildRequires : gcc-locale
BuildRequires : glibc-bin
BuildRequires : glibc-dev
BuildRequires : glibc-doc
BuildRequires : glibc-extras
BuildRequires : glibc-lib-avx2
BuildRequires : glibc-locale
BuildRequires : glibc-nscd
BuildRequires : glibc-staticdev
BuildRequires : glibc-utils
BuildRequires : jansson
BuildRequires : jansson-dev
BuildRequires : libarchive
BuildRequires : libarchive-dev
BuildRequires : libarchive-staticdev
BuildRequires : libcap
BuildRequires : libcap-dev
BuildRequires : libedit
BuildRequires : libedit-dev
BuildRequires : libgcc1
BuildRequires : libstdc++
BuildRequires : libstdc++-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : pkg-config-dev
BuildRequires : python-dev
BuildRequires : python3
BuildRequires : wxWidgets
BuildRequires : wxWidgets-dev
BuildRequires : xz-dev
BuildRequires : xz-staticdev
BuildRequires : zlib-dev
BuildRequires : zlib-staticdev
Patch1: fix-cmake.patch

%description
mhash is a thread-safe hash library, implemented in C, and provides a
uniform interface to a large number of hash algorithms. These 
algorithms can be used to compute checksums, message digests, and 
other signatures. The HMAC support implements the basics for message 
authentication, following RFC 2104.

Algorithms currently supplied are:

CRC-32, CRC-32B, ALDER-32, MD-2, MD-4, MD-5, RIPEMD-128, RIPEMD-160,
RIPEMD-256, RIPEMD-320, SHA-1, SHA-224, SHA-256, SHA-384, SHA-512, HAVAL-128,
HAVAL-160, HAVAL-192, HAVAL-256, TIGER, TIGER-128, TIGER-160, GOST, WHIRLPOOL,
SNEFRU-128, SNEFRU-256

Algorithms will be added to this list over time.

%package bin
Summary: bin components for the wxhexeditor package.
Group: Binaries
Requires: wxhexeditor-data = %{version}-%{release}

%description bin
bin components for the wxhexeditor package.


%package data
Summary: data components for the wxhexeditor package.
Group: Data

%description data
data components for the wxhexeditor package.


%package dev
Summary: dev components for the wxhexeditor package.
Group: Development
Requires: wxhexeditor-bin = %{version}-%{release}
Requires: wxhexeditor-data = %{version}-%{release}
Provides: wxhexeditor-devel = %{version}-%{release}
Requires: wxhexeditor = %{version}-%{release}

%description dev
dev components for the wxhexeditor package.


%prep
%setup -q -n wxhexeditor
cd %{_builddir}/wxhexeditor
%patch1 -p1

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1625813255
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
## altflags1 content
export CFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
## -fno-tree-vectorize: disable -ftree-vectorize thus disable -ftree-loop-vectorize and -ftree-slp-vectorize
## -funroll-loops maybe dangerous
## -Wl,-z,max-page-size=0x1000
export CXXFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -fvisibility-inlines-hidden -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export FCFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
export FFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -Wl,--build-id=sha1"
export CFFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -Wl,--build-id=sha1"
#
export LDFLAGS="-g -O3 --param=lto-max-streaming-parallelism=16 -march=native -mtune=native -fgraphite-identity -Wall -Wl,--as-needed -Wl,--build-id=sha1 -Wl,--enable-new-dtags -Wl,--hash-style=gnu -Wl,-O2 -Wl,-z,now -Wl,-z,relro -falign-functions=32 -flimit-function-alignment -fasynchronous-unwind-tables -fdevirtualize-at-ltrans -floop-nest-optimize -floop-block -fno-math-errno -fno-semantic-interposition -fno-stack-protector -fno-trapping-math -ftree-loop-distribute-patterns -ftree-loop-vectorize -ftree-vectorize -fuse-ld=bfd -fuse-linker-plugin -malign-data=cacheline -feliminate-unused-debug-types -fipa-pta -flto=16 -fno-plt -mtls-dialect=gnu2 -Wl,-sort-common -Wno-error -Wp,-D_REENTRANT -pipe -ffat-lto-objects -fPIC -fomit-frame-pointer -pthread -static-libstdc++ -static-libgcc -lpthread -Wl,--build-id=sha1"
#
export AR=/usr/bin/gcc-ar
export RANLIB=/usr/bin/gcc-ranlib
export NM=/usr/bin/gcc-nm
#
export MAKEFLAGS=%{?_smp_mflags}
#
%global _lto_cflags 1
#global _lto_cflags %{nil}
%global _disable_maintainer_mode 1
#%global _disable_maintainer_mode %{nil}
#
export CCACHE_DISABLE=true
export CCACHE_NOHASHDIR=true
export CCACHE_CPP2=true
export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,file_stat_matches,file_stat_matches_ctime,include_file_ctime,include_file_mtime,modules,system_headers,clang_index_store,file_macro
#export CCACHE_SLOPPINESS=modules,include_file_mtime,include_file_ctime,time_macros,pch_defines,file_stat_matches,clang_index_store,system_headers,locale
#export CCACHE_SLOPPINESS=pch_defines,time_macros,locale,clang_index_store,file_macro
export CCACHE_DIR=/var/tmp/ccache
export CCACHE_BASEDIR=/builddir/build/BUILD
#export CCACHE_LOGFILE=/var/tmp/ccache/cache.debug
#export CCACHE_DEBUG=true
#export CCACHE_NODIRECT=true
#
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/dri:/usr/lib64/haswell:/usr/lib64:/usr/lib:/usr/share"
#
export LIBRARY_PATH="$LIBRARY_PATH:/usr/nvidia/lib64:/usr/nvidia/lib64/vdpau:/usr/nvidia/lib64/xorg/modules/drivers:/usr/nvidia/lib64/xorg/modules/extensions:/usr/local/cuda/lib64:/usr/lib64/dri:/usr/lib64/haswell:/usr/lib64:/usr/lib:/usr/share"
#
export PATH="$PATH:/usr/local/cuda/bin:/usr/nvidia/bin:/usr/bin/haswell:/usr/bin:/usr/sbin"
#
export CPATH="$CPATH:/usr/local/cuda/include"
#
export DISPLAY=:0
export __GL_ALLOW_UNOFFICIAL_PROTOCOL=1
export __GL_SYNC_TO_VBLANK=0
export __GL_SYNC_DISPLAY_DEVICE=DFP-1
export VDPAU_NVIDIA_SYNC_DISPLAY_DEVICE=DFP-1
export LANG=en_US.UTF-8
export XDG_CONFIG_DIRS=/usr/share/xdg:/etc/xdg
export XDG_SEAT=seat0
export XDG_SESSION_TYPE=tty
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_CLASS=user
export XDG_VTNR=1
export XDG_SESSION_ID=1
export XDG_RUNTIME_DIR=/run/user/1000
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export KDE_SESSION_VERSION=5
export KDE_SESSION_UID=1000
export KDE_FULL_SESSION=true
export KDE_APPLICATIONS_AS_SCOPE=1
export VDPAU_DRIVER=nvidia
export LIBVA_DRIVER_NAME=vdpau
export LIBVA_DRIVERS_PATH=/usr/lib64/dri
export GTK_RC_FILES=/etc/gtk/gtkrc
export FONTCONFIG_PATH=/usr/share/defaults/fonts
## altflags1 end
%cmake .. -DCMAKE_BUILD_TYPE=Release
make  %{?_smp_mflags}    V=1 VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1625813255
rm -rf %{buildroot}
## install_macro start
install -dm 0755 %{buildroot}/usr/bin
install -dm 0755 %{buildroot}/usr/lib64
install -dm 0755 %{buildroot}/usr/share/pixmaps
install -dm 0755 %{buildroot}/usr/share/applications
install -dm 0755 %{buildroot}/usr/share/wxHexEditor/templates
install -m 755 -p bin/wxHexEditor %{buildroot}/usr/bin/
install -m 755 -p clr-build/mhash/libmhash.so* %{buildroot}/usr/lib64/
install -m 755 -p clr-build/udis86/libudis.so* %{buildroot}/usr/lib64/
install -m 755 -p resources/wxHexEditor.desktop %{buildroot}/usr/share/applications/
install -m 755 -p resources/wxHexEditor.png %{buildroot}/usr/share/pixmaps/
cp -R -a templates/ %{buildroot}/usr/share/wxHexEditor/
## install_macro end
## install_append content
#install -dm 0755 %{buildroot}/usr/share/imhex/plugins
#install -m 755 -p clr-build/plugins/builtin/builtin.hexplug %{buildroot}/usr/share/imhex/plugins/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/wxHexEditor

%files data
%defattr(-,root,root,-)
/usr/share/applications/wxHexEditor.desktop
/usr/share/pixmaps/wxHexEditor.png
/usr/share/wxHexEditor/templates/Evtx/ChunkHeader.template
/usr/share/wxHexEditor/templates/Evtx/RecordHeader.template
/usr/share/wxHexEditor/templates/ExFAT/FileDirectoryEntry.template
/usr/share/wxHexEditor/templates/ExFAT/FileNameExtensionEntry.template
/usr/share/wxHexEditor/templates/ExFAT/StreamExtensionDirectoryEntry.template
/usr/share/wxHexEditor/templates/ExFAT/VBRExFAT.template
/usr/share/wxHexEditor/templates/ExFAT/VolumeLabelDirectoryEntry.template
/usr/share/wxHexEditor/templates/FAT/FAT12.bin
/usr/share/wxHexEditor/templates/FAT/FAT12.template
/usr/share/wxHexEditor/templates/FAT/FAT32VBR.template
/usr/share/wxHexEditor/templates/HFS+/BTCatalogFileOrFolder.template
/usr/share/wxHexEditor/templates/HFS+/BTCatalogFileOrFolderKey.template
/usr/share/wxHexEditor/templates/HFS+/BTCatalogNodeDescriptor.template
/usr/share/wxHexEditor/templates/HFS+/BTCatalogThread.template
/usr/share/wxHexEditor/templates/HFS+/BTExtentKey.template
/usr/share/wxHexEditor/templates/HFS+/BTHeaderRecord.template
/usr/share/wxHexEditor/templates/HFS+/HFSPlusDataFork-Header.template
/usr/share/wxHexEditor/templates/HFS+/HFSPlusDataFork-One-Extent.template
/usr/share/wxHexEditor/templates/HFS+/HFSPlusVolumeHeader.template
/usr/share/wxHexEditor/templates/LNK/SHELL_LINK_HEADER.Template
/usr/share/wxHexEditor/templates/Logfile/LogRecordHeader.template
/usr/share/wxHexEditor/templates/Logfile/LogRecordOperationHeader.template
/usr/share/wxHexEditor/templates/Logfile/LogRecordPageHeader.template
/usr/share/wxHexEditor/templates/Logfile/RestartPageHeader.template
"/usr/share/wxHexEditor/templates/MBR/EFI-PART (GPT-Header).template"
/usr/share/wxHexEditor/templates/MBR/PartitionTableEntry(GPT).template
/usr/share/wxHexEditor/templates/MBR/PartitionTableEntry(MBR).template
/usr/share/wxHexEditor/templates/NTFS/AttrDef.template
/usr/share/wxHexEditor/templates/NTFS/FNA-Content.template
/usr/share/wxHexEditor/templates/NTFS/MFTRecordHeader.template
/usr/share/wxHexEditor/templates/NTFS/MFTTimestamps.template
/usr/share/wxHexEditor/templates/NTFS/NTFS-VBR.template
/usr/share/wxHexEditor/templates/NTFS/NonResident-NotNamed.template
/usr/share/wxHexEditor/templates/NTFS/ResidentAttributeHeader.template
/usr/share/wxHexEditor/templates/Registry/ACEHex18bytes.template
/usr/share/wxHexEditor/templates/Registry/ACL.template
/usr/share/wxHexEditor/templates/Registry/BaseBlock.template
/usr/share/wxHexEditor/templates/Registry/HBIN_Header.template
/usr/share/wxHexEditor/templates/Registry/NodeKey.template
/usr/share/wxHexEditor/templates/Registry/NodeKeyStructure.bin
/usr/share/wxHexEditor/templates/Registry/NodeKeyStructure.template
/usr/share/wxHexEditor/templates/Registry/SAM_F_ValueData.template
/usr/share/wxHexEditor/templates/Registry/SecurityKey.template
/usr/share/wxHexEditor/templates/Registry/ValueKey.template
/usr/share/wxHexEditor/templates/Registry/lh_SubkeyListEntry.template
/usr/share/wxHexEditor/templates/Registry/lh_li_SubkeyListIndex.template

%files dev
%defattr(-,root,root,-)
/usr/lib64/libmhash.so
/usr/lib64/libudis.so
